### ISSUE TITLE
Support for DS18b20

### ISSUE THREAD

**Issue by svenbla** [RaresAil/homebridge-temperature-sensor-dht#3]
Could you add support for ds18b20 so no humidity and stuff.
Would be great!

**Comment by RaresAil** [comment]
Hey, is the sensor integrated on the PI or you need wiring?

**Comment by svenbla** [comment]
It is not integrated in the pi it's just like the dht22 but it has no humidity sensor and I tried to connect it but it didn't work. If you don't know the sensor google it, it's one of the most famous temperature sensors

**Comment by RaresAil** [comment]
I will work on it

**Comment by RaresAil** [comment]
After more research, i will not add support for that, since the plugin name contains `dht` in it and that sensor is a different type of temperature sensor, i would suggest to try a plugin designed for that sensor.

I found this plugin on NPM: https://www.npmjs.com/package/homebridge-ds18b20

@svenbla
